#ifndef DEV_TOOLS_CPP_LIBRARIES_LIBCEF_LIBBASEDEFAULTS_CEFBASEDEFAULTS_H_
#define DEV_TOOLS_CPP_LIBRARIES_LIBCEF_LIBBASEDEFAULTS_CEFBASEDEFAULTS_H_

class CefBaseApp;

namespace CefBaseDefaults {
   void InstallDefaultHandlers(CefBaseApp& app);
}




#endif /* DEV_TOOLS_CPP_LIBRARIES_LIBCEF_LIBBASEDEFAULTS_CEFBASEDEFAULTS_H_ */
